### PR TITLE
Allow RoadRunner 2023.x

### PR DESCRIPTION
**Pull request by Baldinof**

### CODE REVIEW

**Comment by AlexOstrovsky** [comment]
any luck with this?

**Comment by bitgandtter** [comment]
on a hurry for this to be released. any ETA?

**Comment by Baldinof** [comment]
I'm doing my best to find the time for this.

Would it be ok for you if the minimum required Symfony version is 6.1?

Also the code here should work, if someone can give it a try in a real app, it would be nice.

**Comment by bitgandtter** [comment]
given that latest lts is 5.4 and that this feature is cutting edge at least IMO going for the next sf lts its good enough to 6.1 :+1: on my end

**Comment by AlexOstrovsky** [comment]
This PR will close my issue created earlier #109

**Comment by Baldinof** [comment]
It's mostly good now if someone wants to give it a try.

You have to change your `composer.json` to point to this branch:

```
    "require": {
        ...
        "baldinof/roadrunner-bundle": "dev-rr-2023"
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/baldinof/roadrunner-bundle"
        }
    ],
```

I just want to try some stuff with Doctrine before merging / releasing.

**Comment by bitgandtter** [comment]
I will gave it a try in the next days

**Comment by AlexOstrovsky** [comment]
I can try it next week

**Comment by AlexOstrovsky** [comment]
@Baldinof I tested it today and from my tests everything works with no problems with rr server 2023.1.2

**Comment by Baldinof** [comment]
I just need to review the README and update the CHANGELOG and we should be good here :)

**Comment by AlexOstrovsky** [comment]
nice :) I have it on our testing environment and no problems popped up

**Comment by bitgandtter** [comment]
thanks so much @Baldinof to busy here and haven test it yet. maybe today. but reviewing the changes it does feel like it should work

**Comment by AlexOstrovsky** [comment]
@Baldinof when do you plan to merge and create a release?

**Comment by Baldinof** [comment]
I just released 3.0.0

I need to also upgrade the Symfony recipe and we should be good :)

**Comment by bitgandtter** [comment]
great work @Baldinof appreciated

**Pull request merged**
