### PR TITLE
Remove deprecation messages for ODM integration and worker command

### PR DESCRIPTION
**Pull request by Khazhinov**
Hello! Thanks for the great library!
Symfony started complaining about outdated code, so here's a quick fix for that.

Please note that this fix requires the minimum PHP version to be increased to 8.0

I hope this problem will be fixed in the next major release.

### CODE REVIEW

**Comment by Baldinof** [comment]
@Khazhinov Can add ignores in the phpstan config for the `Attribute class Symfony\Component\Console\Attribute\AsCommand does not exists.` errors in CI?

**Comment by Khazhinov** [comment]
> @Khazhinov Can add ignores in the phpstan config for the `Attribute class Symfony\Component\Console\Attribute\AsCommand does not exists.` errors in CI?

Okay, but:
This error does not exist if using Symfony 6.0+

**Comment by Baldinof** [comment]
Symfony 4.4 is still maintained until november 2023 so I'd like to keep supporting it.

It should not trigger errors at runtime, even if the class does not exists.

**Comment by Khazhinov** [comment]
This is a great
But you can just keep different package versions for different versions of Symfony
This is, of course, IMHO

Thanks!

**Comment by Khazhinov** [comment]
When can we expect a new version with this pr?

**Comment by Baldinof** [comment]
👋 I just released version 3.0.0 which should not trigger deprecations with ODM now.

**Pull request closed without merging**
