### PR TITLE
GRPC support

### PR DESCRIPTION
**Pull request by vsychov**
Hey there,

this PR add support of GRPC protocol (https://spiral.dev/docs/grpc-configuration) to this bundle, and it's drop php 7.3 support (as it's have no active support anymore).

### CODE REVIEW

**Comment by Baldinof** [comment]
Hi!

Thank you for your great work and continuing to improve this bundle :)

For what I understand gRPC is not supported by RoadRunner, it's a plugin that you can add to a custom build or by using the Spiral binary.

For now I want to keep this bundle restricted to RoadRunner, if we merge this, it means that binary that you downloads with `vendor/bin/rr get` will not provide a server able to run all the features of this package.

I know there is a lot of work going on at `spiral/roadrunner` for v2, if gRPC become a full part of RoadRunner, I would be happy to merge this :)

**Comment by Bibob7** [comment]
For us, the optional support for the grpc service would also be very interesting. I think it does not have to be part of the default config, but there will certainly be users who want to use Roadrunner with Symfony and Grpc.

**Comment by StephenBeirlaen** [comment]
Hi, gRPC is now supported for Roadrunner v2: [https://github.com/spiral/roadrunner-grpc](https://github.com/spiral/roadrunner-grpc)
Does this mean that once the CI is fixed, this PR can be reevaluated now?

**Comment by Baldinof** [comment]
Yes, if someone want to revive this I would be glad to help reviewing and merging this :)

**Comment by StephenBeirlaen** [comment]
I think this PR was made before the Symfony Runtime support was introduced here?
If so it might need some improvement.

**Comment by Baldinof** [comment]
Indeed, currently the 2.x branch support Sf Runtime or a worker command for BC reason.

I plan to create a 3.x branch that targets php 8+ and use only the Runtime component.

**Comment by StephenBeirlaen** [comment]
Since I do not have write access to this branch, I had to create a new PR from my fork (I think?): https://github.com/Baldinof/roadrunner-bundle/pull/62

**Comment by vsychov** [comment]
Thanks for migrating it to v2

**Pull request closed without merging**
