### PR TITLE
Stops using deprecated `StreamedResponseListener` in Symfony >=6.1

### LINKED ISSUE #84: StreamedResponseListener deprecated as of Symfony 6.1
Got this on container build
```
In DecoratorServicePass.php line 84:
                                                                                                                                                                 
  The service "Baldinof\RoadRunnerBundle\Integration\Symfony\StreamedResponseListener" has a dependency on a non-existent service "streamed_response_listener".  
 ```

It looks like as of Symfony 6.1 this listener is deprecated.

### PR DESCRIPTION
**Pull request by Baldinof**
Fix #84

### CODE REVIEW

**Comment by Baldinof** [comment]
@brzuchal Can you confirm this works for you?

**Comment by brzuchal** [comment]
@Baldinof how to require it?
I tried `composer update baldinof/roadrunner-bundle:dev-fix-deprecation --no-scripts` with errors

**Comment by brzuchal** [comment]
Ok go tit, `require` instead of `update` in this case.

**Comment by brzuchal** [comment]
@Baldinof can confirm the error message is gone now.

**Comment by patie** [comment]
I also confirm it.

**Comment by bitgandtter** [comment]
question. if Baldinof\RoadRunnerBundle\EventListener\StreamedResponseListener is not anymore, how do send streamed responses from Symfony? I'm trying to use StreamedJsonResponse but always get the full response not chunks of data

**Pull request merged**
