### PR TITLE
Fix: migrate "MASTER_REQUEST" to "MAIN_REQUEST" for Symfony 7 compatibility

### LINKED ISSUE #132: `Undefined constant self::MASTER_REQUEST`
Symfony 7 removed this constant from it's interface and replaced it with `MAIN_REQUEST` https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/HttpKernel/CHANGELOG.md#70

image

### PR DESCRIPTION
**Pull request by FluffyDiscord**
Fixes #132 , backwards compatible up to 5.3

### CODE REVIEW

**Comment by Baldinof** [comment]
Thanks, can you fix the unit test? I will handle phpstan separately

**Comment by FluffyDiscord** [comment]
done

**Comment by Baldinof** [comment]
Thank you, I released 3.0.3 with it :)

**Comment by FluffyDiscord** [comment]
thanks for the quick response!

**Pull request merged**
