### PR TITLE
Followed change of `trusted_headers` and `trusted_proxies` in Symfony 7.2

### PR DESCRIPTION
**Pull request by okorneliuk**
I didn't invent anything, just followed this change in Symfony v7.2

https://github.com/symfony/symfony/pull/58161/files#diff-842527ea5582808ca82ff360aa1f7ceaa44584c9c4b4edd6c27381f62d834d3cR752

### CODE REVIEW

**Comment by okorneliuk** [comment]
@Baldinof Symfony 7.2 is officially released, could you review this real quick?

**Comment by Baldinof** [comment]
Is it compatible with pre 7.2 versions?

**Comment by okorneliuk** [comment]
@Baldinof it should be compatible, since it only adds more types for `kernel.trusted_headers`. As I said, I only repeated the change in Symfony 7.1 -> 7.2

**Comment by Baldinof** [comment]
Alright, I tested it locally and it worked on a 7.2 and a 6.3 sf app.

I just released 3.1.3 which include your PR.

Thank you!

**Pull request merged**
